[versions]
activityCompose = "1.12.0"
agp = "8.13.1"
coil = "3.3.0"
composeBom = "2025.11.01"
detekt = "1.23.8"
detektCompose = "0.4.28"
koin = "4.1.1"
kotlin = "2.2.21"
lifecycleViewmodelNavigation3 = "2.10.0"
material3Expressive = "1.5.0-alpha09"
navigation3 = "1.0.0"
newsflowLibrary = "0.3.4"
serialization = "2.2.21"
serializationJson = "1.9.0"

# SDK versions
compileSdk = "36"
minSdk = "31"
targetSdk = "36"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelNavigation3" }
androidx-material3-expressive = { group = "androidx.compose.material3", name = "material3", version.ref = "material3Expressive" }
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "navigation3" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "navigation3" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-network = { group = "io.coil-kt.coil3", name = "coil-network-ktor3", version.ref = "coil" }
detekt-compose = { group = "io.nlopez.compose.rules", name = "detekt", version.ref = "detektCompose" }
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-compose-viewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel", version.ref = "koin" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serializationJson" }

# NewsflowLibrary
newsflow-library-shared = { group = "io.github.kei-1111.newsflow.library", name = "shared", version.ref = "newsflowLibrary" }
newsflow-library-model = { group = "io.github.kei-1111.newsflow.library", name = "model", version.ref = "newsflowLibrary" }
newsflow-library-home = { group = "io.github.kei-1111.newsflow.library", name = "home", version.ref = "newsflowLibrary" }
newsflow-library-search = { group = "io.github.kei-1111.newsflow.library", name = "search", version.ref = "newsflowLibrary" }
newsflow-library-viewer = { group = "io.github.kei-1111.newsflow.library", name = "viewer", version.ref = "newsflowLibrary" }

# Use build-logic
android-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
detekt-gradle = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
kotlin-gradle = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialization" }

# Convention Plugins
newsflow-android-android-application = { id = "newsflow.android.android.application" }
newsflow-android-android-feature = { id = "newsflow.android.android.feature" }
newsflow-android-android-library = { id = "newsflow.android.android.library" }
newsflow-android-android-library-compose = { id = "newsflow.android.android.library.compose" }
newsflow-android-detekt = { id = "newsflow.android.detekt" }

